M48
; DRILL file {KiCad 7.0.1} date Tue Nov  7 22:06:12 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-07T22:06:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X105.875Y-78.16
X105.875Y-83.94
T2
X102.371Y-91.7
X102.4Y-52.55
X165.7Y-52.5
X165.75Y-91.75
T0
M30
